#! /bin/bash

### install xmonad, a Haskell-based window manager, its default terminal and common utilities for it ###
sudo pacman -Syu
sudo pacman -S xorg-server xorg-xinit xmonad xmonad-contrib xmobar xterm firefox github-cli

#sudo apt install xserver-xorg-core
#sudo apt install xmonad xterm libghc-xmonad-contrib-dev libghc-xmonad-dev suckless-tools
#sudo apt install xinit
cp {.xinitrc,.bash_profile} ~/
mkdir ~/.xmonad
cp xmonad.hs ~/.xmonad/
cp .xmobarrc ~/
cd ~/.xmonad
xmonad --recompile
### end install of xmonad, etc. ###

### setup github ###
#sudo pacman -S firefox github-cli
gh auth login
echo "Please enter git username:"
read USERNAME
git config --global user.name ${USERNAME}
echo "Please enter git email:"
read EMAIL
git config --global user.email ${EMAIL}
### end github setup ###
